---
# tasks file for ansible-clamav

- name: Install ClamAV
  package:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ clamav_packages }}"
    - "{{ clamav_additional_packages }}"

- name: Add ClamAV daily cronjob
  template:
    src: clamav-daily.sh.j2
    dest: /etc/cron.daily/clamav
    owner: root
    group: root
    mode: 0755

- name: Configure ClamAV
  template:
    src: "{{ item }}"
    dest: "/etc/clamav/{{ item | basename | replace('.j2', '') }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart clamav-freshclam
  with_items:
    - "{{ clamav_config_files }}"

- name: Start service to Update Virus DB automatically
  service:
    name: clamav-freshclam
    state: started
    enabled: true
