---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ansible-clamav-ubuntu-18.04
    image: fittest/ubuntu-18.04:latest
    pre_build_image: true
  - name: ansible-clamav-ubuntu-20.04
    image: fittest/ubuntu-20.04:latest
    pre_build_image: true
provisioner:
  name: ansible
  options:
    D: True
scenario:
  name: default
verifier:
  name: goss
  enabled: True
lint: |
  set -e
  yamllint .
  ansible-lint -R .
